# Generated by Django 6.1.1 on 2026-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
