# Generated by Django 6.1.1 on 2026-09-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_is_converted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'webm', 'avi', 'm4v'])]),
        ),
    ]
