# Generated by Django 6.1.1 on 2026-10-01 22:00

from django.db import migrations, models

KNOWN_CATEGORIES = [
    "Action", "Comedy", "Documentary", "Drama", "Nature", "Romance",
]


def normalize_categories(apps, schema_editor):
    """Map free text categories to the fixed ones, unknown ones to Other."""
    video_model = apps.get_model("video_app", "Video")
    known = {name.lower(): name for name in KNOWN_CATEGORIES}
    for video in video_model.objects.all():
        video.category = known.get(video.category.strip().lower(), "Other")
        video.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Nature', 'Nature'), ('Romance', 'Romance'), ('Other', 'Other')], max_length=50),
        ),
        migrations.RunPython(
            normalize_categories, migrations.RunPython.noop
        ),
    ]
